import { useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';

function Icon({ name, size = 20, ...props }: { name: string; size?: number; className?: string }) {
  const paths: Record<string, ReactNode> = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></>,
    folder: <path d="M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z"/>,
    bot: <><rect x="4" y="7" width="16" height="13" rx="4"/><path d="M12 3v4M2 12v4m20-4v4M8 16h8"/><path d="M8 11v1m8-1v1"/></>,
    shield: <><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/></>,
    activity: <><path d="M3 12h4l3-8 4 16 3-8h4"/></>,
    book: <><path d="M12 5v15M3 4c4-1 6 0 9 2 3-2 5-3 9-2v15c-4-1-6 0-9 2-3-2-5-3-9-2V4Z"/></>,
    settings: <><path d="m9 3-1 3-3 1-2 3 2 3v4l3 2 3-1 3 1 3-2v-4l2-3-2-3-3-1-1-3H9Z"/><circle cx="11" cy="11" r="3"/></>,
    arrow: <path d="M4 12h16m-6-6 6 6-6 6"/>,
    chevron: <path d="m9 5 7 7-7 7"/>,
    down: <path d="m7 10 5 5 5-5"/>,
    plus: <path d="M12 5v14M5 12h14"/>,
    bell: <><path d="M5 16V10a7 7 0 0 1 14 0v6l2 2H3l2-2Z"/><path d="M10 21h4"/></>,
    check: <path d="m5 12 4 4L19 6"/>,
    clock: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
    code: <><path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-14-2 16"/></>,
    spark: <><path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Z"/><path d="M20 2v4m-2-2h4"/></>,
    link: <><path d="m9 15 6-6m-7 4-2 2a4 4 0 0 0 6 6l4-4a4 4 0 0 0 0-6M8 13a4 4 0 0 1 0-6l4-4a4 4 0 0 1 6 6l-2 2"/></>,
    external: <><path d="M14 3h7v7m0-7L10 14M10 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-5"/></>,
    close: <path d="m6 6 12 12M6 18 18 6"/>,
    play: <path d="m8 4 12 8-12 8V4Z"/>,
    menu: <path d="M4 6h16M4 12h16M4 18h16"/>,
    info: <><circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/></>,
    search: <><circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/></>,
    logout: <><path d="M10 3H4v18h6m-1-9h12m-4-4 4 4-4 4"/></>,
    lock: <><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" {...props}>{paths[name] || paths.code}</svg>;
}
function EngineLogo({ engine, size = 24 }: { engine: string; size?: number }) {
  return engine === 'Unity' ? <svg width={size} height={size} viewBox="0 0 32 32" fill="currentColor"><path d="m19.7 2 8.8 5.1v10.2l-5.1-3V9.9l-3.7-2.1V2ZM17 7.8l-3.7 2.1 3.7 2.2 3.7-2.2 5.1 3-8.8 5.1-8.8-5.1 5.1-3L17 7.8ZM7 14.1l8.8 5.1v10.2l-5.1-3v-4.3L7 20v-5.9Zm11.5 5.1 8.8-5.1V20l-3.7 2.1v4.3l-5.1 3V19.2ZM4.3 7.1l8.8-5.1v5.8L9.4 9.9v4.4l-5.1 3V7.1Z"/></svg> : <span className="unreal-logo" style={{ width: size, height: size, fontSize: size * .86 }}>U</span>;
}
function HeroArt() {
  return <div className="hero-art" aria-hidden="true"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-dot dot-one"/><div className="art-dot dot-two"/><div className="art-engine unity-tile"><EngineLogo engine="Unity" size={36}/></div><div className="art-engine unreal-tile"><EngineLogo engine="Unreal Engine" size={34}/></div><svg className="cube-art" viewBox="0 0 330 250"><defs><linearGradient id="cubeTop" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#e0ffa1"/><stop offset="1" stopColor="#b0e65e"/></linearGradient><linearGradient id="cubeSide" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#343c2d"/><stop offset="1" stopColor="#161d12"/></linearGradient><filter id="shadow"><feGaussianBlur stdDeviation="12"/></filter></defs><ellipse cx="175" cy="211" rx="78" ry="16" fill="#5e7843" opacity=".18" filter="url(#shadow)"/><path d="m63 171 99-57 108 61-98 57Z" fill="none" stroke="#bac9a9" strokeDasharray="4 5"/><path d="m83 115 79-45 81 45-80 46Z" fill="#3c4634"/><path d="m83 115 80 46v49l-80-46Z" fill="#22291d"/><path d="m163 161 80-46v49l-80 46Z" fill="#11180e"/><path d="m94 95 69-40 69 40-69 40Z" fill="url(#cubeTop)"/><path d="m94 95 69 40v45l-69-40Z" fill="#a8d86c"/><path d="m163 135 69-40v45l-69 40Z" fill="#8ab84f"/><path d="m108 64 55-32 56 32-56 32Z" fill="#394530"/><path d="m108 64 55 32v46l-55-32Z" fill="url(#cubeSide)"/><path d="m163 96 56-32v46l-56 32Z" fill="#192113"/><path d="m145 65 17-10 19 10-8 5-11-6-8 5 11 6-8 5-19-11 7-4Z" fill="#c4f38c"/><path d="m107 116 14 8m-14-2 8 5" stroke="#e2ffbb" strokeWidth="2"/><path d="m181 161 27-16" stroke="#bdeb81" strokeWidth="2"/><circle cx="225" cy="184" r="12" fill="#fff" stroke="#dde8d2"/><path d="m220 184 4 4 7-8" fill="none" stroke="#659d2c" strokeWidth="2"/></svg><div className="art-tag"><span className="status-dot"/> Built for your engine</div></div>;
}
const initialProjects = [
  { name: 'Forest Adventure', path: 'D:/Unity Projects/Forest Adventure', engine: 'Unity', version: '2022.3 LTS', time: '2 hours ago', tone: 'forest', letter: 'F' },
  { name: 'Project Nova', path: 'D:/Unreal Projects/Project Nova', engine: 'Unreal Engine', version: '5.3', time: 'Yesterday', tone: 'nova', letter: 'N' },
  { name: 'Kart Racer', path: 'D:/Unity Projects/Kart Racer', engine: 'Unity', version: '2023.2', time: '2 days ago', tone: 'kart', letter: 'K' },
];
const agents = [
  { name: 'Code Architect', desc: 'Plans and writes engine-ready code', icon: 'code', tone: 'violet' },
  { name: 'Code Validator', desc: 'Checks compatibility before every write', icon: 'shield', tone: 'green' },
  { name: 'Project Assistant', desc: 'Understands your project, end to end', icon: 'spark', tone: 'orange' },
];
export default function App() {
  const [page, setPage] = useState('Overview');
  const [engine, setEngine] = useState('Unity');
  const [directory, setDirectory] = useState('');
  const [error, setError] = useState('');
  const [projects, setProjects] = useState(initialProjects);
  const [modal, setModal] = useState<string | null>(null);
  const [selectedProject, setSelectedProject] = useState(initialProjects[0]);
  const [toast, setToast] = useState('');
  const [connecting, setConnecting] = useState(false);
  const [notifications, setNotifications] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [agentRunning, setAgentRunning] = useState(false);
  const [agentResult, setAgentResult] = useState(false);
  const [prompt, setPrompt] = useState('Create a smooth third-person player controller');
  const [code, setCode] = useState('using UnityEngine;\n\npublic class PlayerController : MonoBehaviour\n{\n    public float speed = 5f;\n\n    void Update()\n    {\n        float move = Input.GetAxis("Horizontal");\n        transform.Translate(Vector3.right * move * speed * Time.deltaTime);\n    }\n}');
  const [validation, setValidation] = useState<string[] | null>(null);
  const [validating, setValidating] = useState(false);
  const [search, setSearch] = useState('');
  const [autoValidate, setAutoValidate] = useState(true);
  const folderInput = useRef<HTMLInputElement>(null);
  const directoryInput = useRef<HTMLInputElement>(null);
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 4000); return () => clearTimeout(timer); } }, [toast]);
  useEffect(() => { const close = (e: KeyboardEvent) => { if (e.key === 'Escape') { setModal(null); setNotifications(false); } }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, []);
  const navigate = (next: string) => { setPage(next); setMenuOpen(false); };
  function connect() {
    if (!directory.trim()) { setError('Enter your project directory or choose a folder to continue.'); directoryInput.current?.focus(); return; }
    setError(''); setConnecting(true);
    setTimeout(() => {
      const name = directory.trim().replace(/[/\\]+$/, '').split(/[/\\]/).pop() || 'My project';
      const project = { name, path: directory, engine, version: engine === 'Unity' ? '2022.3 LTS' : '5.3', time: 'Just now', tone: 'forest', letter: name[0].toUpperCase() };
      setProjects(prev => [project, ...prev.filter(p => p.path !== directory)]); setSelectedProject(project); setConnecting(false); setModal('project'); setToast('Project added to your preview workspace');
    }, 900);
  }
  function validate() {
    setValidating(true); setValidation(null);
    setTimeout(() => {
      const issues: string[] = [];
      if (!code.trim()) issues.push('Add some code before running validation.');
      else { if (engine === 'Unity' && !code.includes('UnityEngine')) issues.push('UnityEngine namespace is missing.'); if (engine === 'Unreal Engine' && !/#include/.test(code)) issues.push('Unreal C++ code should include its required engine headers.'); if ((code.match(/{/g) || []).length !== (code.match(/}/g) || []).length) issues.push('Opening and closing braces do not match.'); if (engine === 'Unity' && code.includes('DestroyImmediate')) issues.push('DestroyImmediate is intended for editor code; use Destroy at runtime.'); }
      setValidation(issues); setValidating(false);
    }, 1100);
  }
  function runAgent() { if (!prompt.trim()) return; setAgentRunning(true); setAgentResult(false); setTimeout(() => { setAgentRunning(false); setAgentResult(true); }, 1600); }
  const openValidator = () => { setValidation(null); setModal('validator'); };
  const projectList = projects.filter(p => p.name.toLowerCase().includes(search.toLowerCase()));
  return <div className="site-shell">
    {menuOpen && <div className="sidebar-backdrop" onClick={() => setMenuOpen(false)}/>}
    <aside className={`sidebar ${menuOpen ? 'is-open' : ''}`}>
      <a className="brand" href="#" onClick={e => { e.preventDefault(); navigate('Overview'); }}><span className="brand-symbol"><svg width="25" height="28" viewBox="0 0 25 28" fill="none"><path d="M4 6 21 1v7L11 11v5l8-2v6l-8 2v5l-7-4V6Z" fill="currentColor"/></svg></span>forge<span className="brand-period">.</span></a>
      <div className="workspace-switch"><span className="workspace-icon">A<span>✦</span></span><div><strong>Alex's workspace</strong><span>Personal workspace</span></div><Icon name="down" size={16}/></div>
      <div className="nav-label">WORKSPACE</div>
      <nav>{[['Overview','grid'],['Projects','folder'],['AI Agents','bot'],['Code Validator','shield'],['Activity','activity']].map(([label, icon]) => <button key={label} className={`nav-item ${page === label ? 'active' : ''}`} onClick={() => navigate(label)}><Icon name={icon} size={19}/><span>{label}</span>{label === 'AI Agents' && <span className="nav-count">3</span>}{label === 'Overview' && page === label && <span className="nav-active-dot"/>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="nav-label">RESOURCES</div><button className="nav-item" onClick={() => setModal('docs')}><Icon name="book" size={19}/><span>Documentation</span><Icon name="external" size={13}/></button><button className="nav-item" onClick={() => setModal('settings')}><Icon name="settings" size={19}/><span>Settings</span></button><div className="build-card"><span className="build-icon"><Icon name="spark" size={20}/></span><strong>A little AI. A lot of possibility.</strong><p>Less busywork. More building.<br/>Let's bring your ideas to life.</p><button onClick={() => setModal('guide')}>Explore what's possible <Icon name="arrow" size={16}/></button></div><button className="user-profile" onClick={() => setModal('profile')}><span className="avatar">AL</span><span><strong>Alex Morgan</strong><small>Personal account</small></span><Icon name="down" size={16}/></button></div>
      <div className="sidebar-footer"><span className="status-dot"/> All systems operational <span>v.1.0</span></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="mobile-menu icon-button" aria-label="Open navigation" onClick={() => setMenuOpen(!menuOpen)}><Icon name="menu"/></button><span>Workspace</span><Icon name="chevron" size={13}/><strong>{page}</strong></div><div className="topbar-right"><span className="preview-badge">EARLY ACCESS</span><span className="topbar-divider"/><div className="notification-wrap"><button className="icon-button notification-button" aria-label="Notifications" onClick={() => setNotifications(!notifications)}><Icon name="bell" size={20}/><i/></button>{notifications && <div className="notifications-popover"><strong>You're all caught up</strong><p>Your workspace is ready. Connect a project to start exploring.</p><span>Frontend preview · no live notifications</span></div>}</div><button className="avatar avatar-small" onClick={() => setModal('profile')} aria-label="Open profile">AL</button></div></header>
      <main>
        <div className="page-heading"><div><div className="eyebrow">YOUR CREATIVE COMMAND CENTER</div><h1>{page === 'Overview' ? 'Great ideas start here.' : page === 'Projects' ? 'Your next world is waiting.' : page === 'AI Agents' ? 'Meet your new dream team.' : page === 'Code Validator' ? 'Build with confidence.' : 'Every step, in one place.'}<span className="heading-dot">.</span></h1><p>{page === 'Overview' ? 'Connect your project. Meet your agents. Build something extraordinary.' : page === 'Projects' ? 'A home for every project, from first idea to final build.' : page === 'AI Agents' ? 'Specialized AI teammates, designed around your game engine.' : page === 'Code Validator' ? 'Engine-aware checks. Better code. Fewer surprises.' : 'Keep track of what’s happening across your workspace.'}</p></div><button className="button button-white heading-action" onClick={() => setModal('guide')}><Icon name="play" size={14}/> Quick start guide <Icon name="external" size={13}/></button></div>
        {page === 'Overview' && <section className="hero"><div className="hero-content"><span className="hero-kicker"><span className="tiny-spark">✦</span> YOUR VISION. YOUR ENGINE. YOUR AI TEAM.</span><h2>You build the world.<br/>We'll handle the groundwork.</h2><p>AI agents that understand your Unity and Unreal projects.<br className="desktop-break"/> Plan, validate, and write code — with you in control.</p><button className="button button-dark" onClick={() => { directoryInput.current?.focus(); directoryInput.current?.scrollIntoView({ behavior: 'smooth', block: 'center' }); }}>Let's build something <Icon name="arrow" size={17}/></button><div className="hero-compatibility"><span><EngineLogo engine="Unity" size={17}/> Unity</span><i/><span><EngineLogo engine="Unreal Engine" size={17}/> Unreal Engine</span><span className="compatibility-note">Built for the engines you love</span></div></div><HeroArt/></section>}
        {(page === 'Overview' || page === 'Projects') && <div className={`workspace-grid ${page === 'Projects' ? 'projects-view' : ''}`}><section className="panel connect-panel"><div className="panel-heading"><span className="section-icon"><Icon name="folder" size={19}/></span><div><h2>Connect your project</h2><p>Your next chapter starts with a directory.</p></div><span className="step-badge">STEP 01</span></div><label className="field-label">Game engine</label><div className="engine-options">{['Unity', 'Unreal Engine'].map(e => <button key={e} className={`engine-option ${engine === e ? 'selected' : ''}`} onClick={() => setEngine(e)}><EngineLogo engine={e} size={24}/><strong>{e}</strong><span className="radio-circle">{engine === e && <span/>}</span></button>)}</div><label className="field-label directory-label" htmlFor="directory">Project directory <span>Local project path</span></label><div className={`directory-field ${error ? 'has-error' : ''}`}><Icon name="folder" size={18}/><input id="directory" ref={directoryInput} value={directory} onChange={e => { setDirectory(e.target.value); setError(''); }} onKeyDown={e => e.key === 'Enter' && connect()} placeholder={engine === 'Unity' ? 'e.g. D:/Projects/MyUnityGame' : 'e.g. D:/Projects/MyUnrealGame'}/><button onClick={() => folderInput.current?.click()}>Browse <Icon name="folder" size={14}/></button><input className="hidden" type="file" ref={folderInput} {...({ webkitdirectory: '', directory: '' } as any)} onChange={e => { const file = e.target.files?.[0]; if (file) { setDirectory(file.webkitRelativePath.split('/')[0]); setError(''); setToast('Folder selected. Files stay on your device.'); } }}/></div>{error ? <p className="field-error">{error}</p> : <p className="field-help"><Icon name="info" size={13}/> Select the root folder of your Unity or Unreal project.</p>}<div className="connect-bottom"><span><Icon name="shield" size={15}/> Your code stays yours. Always.</span><button className="button button-lime" onClick={connect} disabled={connecting}>{connecting ? 'Connecting…' : 'Connect project'}<Icon name="arrow" size={16}/></button></div></section><section className="panel agents-panel"><div className="panel-heading"><span className="section-icon"><Icon name="bot" size={20}/></span><div><h2>Your AI dream team</h2><p>Specialists that work better, together.</p></div><span className="ready-badge"><span className="status-dot"/> Ready</span></div><div className="agent-list">{agents.map(a => <button className="agent-row" key={a.name} onClick={() => { if (a.name === 'Code Validator') openValidator(); else { setModal(a.name); setAgentResult(false); } }}><span className={`agent-icon ${a.tone}`}><Icon name={a.icon} size={20}/></span><span className="agent-info"><strong>{a.name}</strong><small>{a.desc}</small></span><Icon name="chevron" size={15}/></button>)}</div><button className="agents-bottom" onClick={() => navigate('AI Agents')}>Meet your agents <Icon name="arrow" size={16}/></button></section></div>}
        {(page === 'Overview' || page === 'Projects') && <div className="lower-grid"><section className="panel recent-panel"><div className="simple-heading"><h2>Recent projects <span className="number-badge">{projects.length}</span></h2>{page === 'Overview' ? <button className="text-button" onClick={() => navigate('Projects')}>View all <Icon name="arrow" size={14}/></button> : <div className="search-field"><Icon name="search" size={14}/><input aria-label="Search projects" placeholder="Search projects" value={search} onChange={e => setSearch(e.target.value)}/></div>}</div><div className="project-table"><div className="project-table-head"><span>PROJECT NAME</span><span>LAST OPENED</span><span/></div>{projectList.map((p, i) => <button className="project-row" key={p.path + i} onClick={() => { setSelectedProject(p); setModal('project'); }}><span className="project-main"><span className={`project-avatar ${p.tone}`}>{p.letter}<span>✦</span></span><span><strong>{p.name}</strong><small><EngineLogo engine={p.engine} size={12}/>{p.engine}<span className="version-dot">·</span>{p.version}</small></span></span><span className="project-time">{p.time}</span><Icon name="chevron" size={15}/></button>)}{projectList.length === 0 && <p className="empty-state">No projects match your search.</p>}</div></section><section className="validation-card"><div className="validation-heading"><span className="validation-icon"><Icon name="shield" size={22}/></span><span className="always-on">ALWAYS A STEP AHEAD</span></div><h2>Good code. Before it’s your code.</h2><p>Every change is validated against your engine's APIs and best practices, before it's written to your project.</p><div className="check-pills"><span><Icon name="check" size={13}/> Engine-aware</span><span><Icon name="check" size={13}/> Safer by default</span></div><button className="text-button" onClick={openValidator}>Explore code validation <Icon name="arrow" size={15}/></button></section></div>}
        {page === 'AI Agents' && <><div className="agent-detail-grid">{agents.map(a => <section className="panel agent-detail-card" key={a.name}><div className={`agent-icon ${a.tone}`}><Icon name={a.icon} size={28}/></div><span className="ready-badge"><span className="status-dot"/> Ready</span><h2>{a.name}</h2><p>{a.desc}. {a.name === 'Code Architect' ? 'Turn your ideas into a clear implementation plan and practical code.' : a.name === 'Code Validator' ? 'Preview engine-specific checks and catch common issues early.' : 'Explore your project structure and find the right next step.'}</p><button className="button button-white" onClick={() => { setAgentResult(false); a.name === 'Code Validator' ? openValidator() : setModal(a.name); }}>Explore agent <Icon name="arrow" size={16}/></button></section>)}</div><div className="inline-notice"><Icon name="info" size={18}/><p>This is your frontend sandbox. Agent responses are sample previews; no AI service is connected and no project files are modified.</p></div></>}
        {page === 'Code Validator' && <section className="panel standalone-validator"><div className="validator-intro"><span className="agent-icon green"><Icon name="shield" size={28}/></span><h2>Validate first. Create confidently.</h2><p>Try a lightweight, browser-based preview of engine-aware code validation.</p><div className="validation-features"><span><Icon name="check" size={16}/> Engine namespace checks</span><span><Icon name="check" size={16}/> Balanced brace checks</span><span><Icon name="check" size={16}/> Common API warnings</span></div><button className="button button-lime" onClick={openValidator}>Open code validator <Icon name="code" size={17}/></button><small>This demo is not a compiler. Actual validation requires your engine's toolchain.</small></div><div className="code-preview"><div className="code-preview-top"><span className="status-dot"/> PlayerController.cs <span>C#</span></div><pre>{code}</pre><div className="code-preview-footer"><Icon name="shield" size={16}/> A safer starting point for every build</div></div></section>}
        {page === 'Activity' && <section className="panel activity-panel"><div className="simple-heading"><h2>Workspace activity</h2><span className="subtle-tag">Demo timeline</span></div>{projects.map((p, i) => <div className="timeline-row" key={p.path + i}><span className={`agent-icon ${i === 0 ? 'green' : 'violet'}`}><Icon name={i === 0 ? 'link' : 'shield'} size={20}/></span><div><strong>{i === 0 ? 'Project added to workspace' : 'Validation preview completed'}</strong><p>{p.name} <span>· {p.engine}</span></p></div><span>{p.time}</span></div>)}</section>}
        <footer className="main-footer"><span><Icon name="lock" size={13}/> Built for creators. Designed for peace of mind.</span><span>Frontend preview <i/> No files are modified <span className="footer-spark">✦</span></span></footer>
      </main>
    </div>
    {toast && <div className="toast" role="status"><span className="toast-check"><Icon name="check" size={16}/></span>{toast}<button className="icon-button" onClick={() => setToast('')} aria-label="Dismiss notification"><Icon name="close" size={15}/></button></div>}
    {modal && <div className="modal-backdrop" onClick={e => { if (e.target === e.currentTarget) setModal(null); }}><section className={`modal ${modal === 'validator' ? 'wide-modal' : ''}`} role="dialog" aria-modal="true" aria-label={modal === 'validator' ? 'Code validator' : modal}><button className="modal-close icon-button" onClick={() => setModal(null)} aria-label="Close dialog"><Icon name="close"/></button>
      {modal === 'validator' ? <><span className="modal-eyebrow"><Icon name="shield" size={17}/> VALIDATE BEFORE YOU CREATE</span><h2>A second pair of eyes for your code.</h2><p className="modal-description">Try basic engine-aware checks. This frontend demo does not compile code or access your project.</p><div className="validator-toolbar"><div className="segmented-control">{['Unity','Unreal Engine'].map(e => <button className={engine === e ? 'selected' : ''} onClick={() => { setEngine(e); setValidation(null); }} key={e}><EngineLogo engine={e} size={16}/>{e}</button>)}</div><span>{engine === 'Unity' ? 'C#' : 'C++'} · Editable preview</span></div><textarea className="code-editor" value={code} onChange={e => { setCode(e.target.value); setValidation(null); }} spellCheck={false} aria-label="Code to validate"/>{validation && <div className={`validation-result ${validation.length ? 'has-issues' : ''}`}><strong><Icon name={validation.length ? 'info' : 'check'} size={17}/>{validation.length ? `${validation.length} ${validation.length === 1 ? 'issue' : 'issues'} to review` : 'Basic checks passed'}</strong>{validation.length ? <ul>{validation.map(issue => <li key={issue}>{issue}</li>)}</ul> : <p>No issues found in these limited checks. Validate with the {engine} compiler before use.</p>}</div>}<div className="modal-actions"><span><Icon name="shield" size={14}/> Runs locally in your browser</span><button className="button button-lime" disabled={validating} onClick={validate}>{validating ? 'Checking code…' : 'Validate code'}<Icon name="arrow" size={16}/></button></div></>
      : modal === 'project' ? <><span className={`project-avatar large ${selectedProject.tone}`}>{selectedProject.letter}<span>✦</span></span><h2>{selectedProject.name}</h2><p className="modal-description">Your project's preview workspace is ready.</p><div className="project-details"><div><span>Game engine</span><strong><EngineLogo engine={selectedProject.engine} size={20}/>{selectedProject.engine}</strong></div><div><span>Project directory</span><code>{selectedProject.path}</code></div><div><span>Available agents</span><strong>3 specialists ready to help</strong></div></div><div className="inline-notice"><Icon name="info" size={18}/><p>Preview only. Pasting a path doesn't grant access to your files. A desktop integration would be needed to read or edit your project.</p></div><button className="button button-lime full-width" onClick={() => { setEngine(selectedProject.engine); setAgentResult(false); setModal('Code Architect'); }}>Meet your Code Architect <Icon name="arrow" size={16}/></button></>
      : modal === 'Code Architect' || modal === 'Project Assistant' ? <><span className="agent-icon violet"><Icon name={modal === 'Code Architect' ? 'code' : 'spark'} size={25}/></span><h2>{modal}</h2><p className="modal-description">Give your AI teammate an idea. Explore a sample planning workflow below.</p><label className="field-label" htmlFor="agent-prompt">What would you like to build?</label><textarea id="agent-prompt" className="prompt-input" value={prompt} onChange={e => setPrompt(e.target.value)}/><button className="button button-lime full-width" onClick={runAgent} disabled={agentRunning || !prompt.trim()}>{agentRunning ? 'Preparing your preview…' : 'Preview agent workflow'}<Icon name="spark" size={16}/></button>{agentResult && <div className="agent-result"><span className="subtle-tag">SAMPLE RESPONSE · NOT AI-GENERATED</span><h3>Here's how we'd approach it</h3><p className="request-echo">Your idea: “{prompt}”</p><ol><li><strong>Understand the project</strong><p>Review your {engine} version, scripts, and existing architecture.</p></li><li><strong>Plan the implementation</strong><p>Break the request into small, reviewable changes.</p></li><li><strong>{autoValidate ? 'Validate before writing' : 'Review before writing'}</strong><p>{autoValidate ? 'Check engine APIs and compilation, then ask for your approval.' : 'Review each proposed change and ask for your approval. Engine validation is still recommended.'}</p></li></ol><button className="text-button" onClick={openValidator}>Try the validation preview <Icon name="arrow" size={15}/></button></div>}<p className="modal-footnote">No live AI connection. Nothing is written to your project.</p></>
      : modal === 'guide' || modal === 'docs' ? <><span className="modal-eyebrow"><Icon name="book" size={17}/> THE FORGE FIELD GUIDE</span><h2>From an idea to your next great game.</h2><p className="modal-description">Your engine. Your creative process. A little extra support.</p><div className="guide-steps">{[['01','Bring your project','Choose Unity or Unreal Engine and paste your project’s root directory. You can also select a folder.'],['02','Work with your team','Explore the Code Architect, Code Validator, and Project Assistant. Each has a focused role.'],['03','Review, validate, create','Preview code checks, review the plan, and stay in control of every proposed change.']].map(([n,title,desc]) => <div key={n}><span>{n}</span><div><h3>{title}</h3><p>{desc}</p></div></div>)}</div><div className="inline-notice"><Icon name="info" size={18}/><p>This is an interactive website concept. Real AI agents, engine compilation, and local file editing would require a backend and desktop integration.</p></div><button className="button button-lime full-width" onClick={() => { setModal(null); navigate('Projects'); setTimeout(() => directoryInput.current?.focus(), 50); }}>Explore the project preview <Icon name="arrow" size={16}/></button></>
      : modal === 'settings' ? <><span className="modal-eyebrow"><Icon name="settings" size={17}/> MAKE YOURSELF AT HOME</span><h2>Workspace preferences</h2><p className="modal-description">Customize this browser session.</p><label className="field-label" htmlFor="default-engine">Preferred game engine</label><select id="default-engine" className="select-field" value={engine} onChange={e => setEngine(e.target.value)}><option>Unity</option><option>Unreal Engine</option></select><div className="setting-row"><div><strong>Validation-first workflow</strong><p>Show validation as a step before writing code.</p></div><button role="switch" aria-checked={autoValidate} aria-label="Validation-first workflow" className={`toggle ${autoValidate ? 'on' : ''}`} onClick={() => setAutoValidate(!autoValidate)}><span/></button></div><button className="button button-lime full-width" onClick={() => { setModal(null); setToast('Workspace preferences updated for this session'); }}>Save preferences <Icon name="check" size={16}/></button></>
      : <><span className="avatar profile-avatar">AL</span><h2>Alex Morgan</h2><p className="modal-description">A little imagination. Unlimited possibilities.</p><div className="project-details"><div><span>Workspace</span><strong>Alex's workspace</strong></div><div><span>Account type</span><strong>Personal · Early access</strong></div><div><span>Projects in this session</span><strong>{projects.length} projects</strong></div></div><p className="modal-footnote">This is a sample profile for the Forge website preview.</p><button className="button button-white full-width" onClick={() => setModal('settings')}>Workspace settings <Icon name="settings" size={16}/></button></>}
    </section></div>}
  </div>;
}
